<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container5FAcTet\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container5FAcTet/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container5FAcTet.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container5FAcTet\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container5FAcTet\App_KernelDevDebugContainer([
    'container.build_hash' => '5FAcTet',
    'container.build_id' => 'a0e6bf3b',
    'container.build_time' => 1609006251,
], __DIR__.\DIRECTORY_SEPARATOR.'Container5FAcTet');
