<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container0gP4cTh\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container0gP4cTh/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container0gP4cTh.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container0gP4cTh\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container0gP4cTh\App_KernelDevDebugContainer([
    'container.build_hash' => '0gP4cTh',
    'container.build_id' => 'fb2b2208',
    'container.build_time' => 1607267914,
], __DIR__.\DIRECTORY_SEPARATOR.'Container0gP4cTh');
