<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCv73u4w\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCv73u4w/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCv73u4w.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCv73u4w\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerCv73u4w\App_KernelDevDebugContainer([
    'container.build_hash' => 'Cv73u4w',
    'container.build_id' => 'bdc074f4',
    'container.build_time' => 1606842264,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCv73u4w');
