<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTCHHrLM\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTCHHrLM/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTCHHrLM.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTCHHrLM\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerTCHHrLM\App_KernelDevDebugContainer([
    'container.build_hash' => 'TCHHrLM',
    'container.build_id' => 'e894aee6',
    'container.build_time' => 1606595940,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTCHHrLM');
