<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerN6zar7a\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerN6zar7a/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerN6zar7a.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerN6zar7a\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerN6zar7a\App_KernelDevDebugContainer([
    'container.build_hash' => 'N6zar7a',
    'container.build_id' => 'e78fdd1a',
    'container.build_time' => 1608073381,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerN6zar7a');
