<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOxE3OuA\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOxE3OuA/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOxE3OuA.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOxE3OuA\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerOxE3OuA\App_KernelDevDebugContainer([
    'container.build_hash' => 'OxE3OuA',
    'container.build_id' => '98c8aea8',
    'container.build_time' => 1606067633,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOxE3OuA');
