<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerG9x14ws\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerG9x14ws/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerG9x14ws.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerG9x14ws\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerG9x14ws\App_KernelDevDebugContainer([
    'container.build_hash' => 'G9x14ws',
    'container.build_id' => '99e2d55e',
    'container.build_time' => 1608161491,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerG9x14ws');
