<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGFvcBsf\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGFvcBsf/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGFvcBsf.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGFvcBsf\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerGFvcBsf\App_KernelDevDebugContainer([
    'container.build_hash' => 'GFvcBsf',
    'container.build_id' => '683d1998',
    'container.build_time' => 1609247932,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGFvcBsf');
