<?php

namespace Container6TZI4x9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator__SfIDOzService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator..sfIDOz' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator..sfIDOz'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\ProgramController::show' => ['privates', '.service_locator.6Q3SUSI', 'get_ServiceLocator_6Q3SUSIService', true],
            'App\\Controller\\ProgramController::showEpisode' => ['privates', '.service_locator.RJhid1v', 'get_ServiceLocator_RJhid1vService', true],
            'App\\Controller\\ProgramController::showSeason' => ['privates', '.service_locator.U7HHBPP', 'get_ServiceLocator_U7HHBPPService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel::terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
            'App\\Controller\\ProgramController:show' => ['privates', '.service_locator.6Q3SUSI', 'get_ServiceLocator_6Q3SUSIService', true],
            'App\\Controller\\ProgramController:showEpisode' => ['privates', '.service_locator.RJhid1v', 'get_ServiceLocator_RJhid1vService', true],
            'App\\Controller\\ProgramController:showSeason' => ['privates', '.service_locator.U7HHBPP', 'get_ServiceLocator_U7HHBPPService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel:terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
        ], [
            'App\\Controller\\ProgramController::show' => '?',
            'App\\Controller\\ProgramController::showEpisode' => '?',
            'App\\Controller\\ProgramController::showSeason' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\ProgramController:show' => '?',
            'App\\Controller\\ProgramController:showEpisode' => '?',
            'App\\Controller\\ProgramController:showSeason' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
