<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCnIxvxK\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCnIxvxK/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCnIxvxK.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCnIxvxK\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerCnIxvxK\App_KernelDevDebugContainer([
    'container.build_hash' => 'CnIxvxK',
    'container.build_id' => 'bfce7c39',
    'container.build_time' => 1609433138,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCnIxvxK');
