<?php

namespace ContainerUmGIRs2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_CjG2UiAService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.CjG2UiA' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.CjG2UiA'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'episodeRepository' => ['privates', 'App\\Repository\\EpisodeRepository', 'getEpisodeRepositoryService', true],
        ], [
            'episodeRepository' => 'App\\Repository\\EpisodeRepository',
        ]);
    }
}
