<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerANtE8oo\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerANtE8oo/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerANtE8oo.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerANtE8oo\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerANtE8oo\App_KernelDevDebugContainer([
    'container.build_hash' => 'ANtE8oo',
    'container.build_id' => 'b73883cb',
    'container.build_time' => 1607286341,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerANtE8oo');
