<?php

namespace ContainerIZCL1yj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_BBk2hOyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.bBk2hOy' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.bBk2hOy'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'episode' => ['privates', '.errored..service_locator.bBk2hOy.App\\Entity\\Episode', NULL, 'Cannot autowire service ".service_locator.bBk2hOy": it references class "App\\Entity\\Episode" but no such service exists.'],
            'slugify' => ['privates', 'App\\Service\\Slugify', 'getSlugifyService', true],
        ], [
            'episode' => 'App\\Entity\\Episode',
            'slugify' => 'App\\Service\\Slugify',
        ]);
    }
}
