<?php

namespace ContainerIZCL1yj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSeason2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.U7HHBPP.App\Entity\Season' shared service.
     *
     * @return \App\Entity\Season
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.U7HHBPP": it references class "App\\Entity\\Season" but no such service exists.');
    }
}
