<?php

namespace ContainerIZCL1yj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSlugifyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\Slugify' shared autowired service.
     *
     * @return \App\Service\Slugify
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/Slugify.php';

        return $container->privates['App\\Service\\Slugify'] = new \App\Service\Slugify();
    }
}
