<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNes2EEq\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNes2EEq/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNes2EEq.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNes2EEq\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerNes2EEq\App_KernelDevDebugContainer([
    'container.build_hash' => 'Nes2EEq',
    'container.build_id' => '0938becd',
    'container.build_time' => 1607383325,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNes2EEq');
