<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAGo38mx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAGo38mx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerAGo38mx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerAGo38mx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerAGo38mx\App_KernelDevDebugContainer([
    'container.build_hash' => 'AGo38mx',
    'container.build_id' => 'cab7906b',
    'container.build_time' => 1607646079,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAGo38mx');
