<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerE42mFyE\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerE42mFyE/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerE42mFyE.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerE42mFyE\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerE42mFyE\App_KernelDevDebugContainer([
    'container.build_hash' => 'E42mFyE',
    'container.build_id' => 'd8942045',
    'container.build_time' => 1607044702,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerE42mFyE');
