<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWPg2jSN\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWPg2jSN/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWPg2jSN.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWPg2jSN\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerWPg2jSN\App_KernelDevDebugContainer([
    'container.build_hash' => 'WPg2jSN',
    'container.build_id' => '9bfa968d',
    'container.build_time' => 1606669289,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWPg2jSN');
