<?php

namespace ContainerAuZTQBs;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_LOjmvR_Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.LOjmvR.' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.LOjmvR.'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'program' => ['privates', '.errored..service_locator.LOjmvR..App\\Entity\\Program', NULL, 'Cannot autowire service ".service_locator.LOjmvR.": it references class "App\\Entity\\Program" but no such service exists.'],
            'slugify' => ['privates', 'App\\Service\\Slugify', 'getSlugifyService', true],
        ], [
            'program' => 'App\\Entity\\Program',
            'slugify' => 'App\\Service\\Slugify',
        ]);
    }
}
