<?php

namespace ContainerAuZTQBs;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Rx6v_RCService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.rx6v.RC' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.rx6v.RC'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'slugify' => ['privates', 'App\\Service\\Slugify', 'getSlugifyService', true],
        ], [
            'slugify' => 'App\\Service\\Slugify',
        ]);
    }
}
