<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerC6YQjxq\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerC6YQjxq/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerC6YQjxq.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerC6YQjxq\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerC6YQjxq\App_KernelDevDebugContainer([
    'container.build_hash' => 'C6YQjxq',
    'container.build_id' => '030af069',
    'container.build_time' => 1609193408,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerC6YQjxq');
