<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEqCcCSB\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEqCcCSB/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerEqCcCSB.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerEqCcCSB\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerEqCcCSB\App_KernelDevDebugContainer([
    'container.build_hash' => 'EqCcCSB',
    'container.build_id' => '2deb9a0f',
    'container.build_time' => 1607005345,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEqCcCSB');
