<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container5F20Nui\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container5F20Nui/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container5F20Nui.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container5F20Nui\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container5F20Nui\App_KernelDevDebugContainer([
    'container.build_hash' => '5F20Nui',
    'container.build_id' => '545c4e10',
    'container.build_time' => 1609799861,
], __DIR__.\DIRECTORY_SEPARATOR.'Container5F20Nui');
