<?php

namespace ContainerRX9hBPo;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_KKWZSFEService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.KKWZSFE' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.KKWZSFE'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'program' => ['privates', '.errored..service_locator.KKWZSFE.App\\Entity\\Program', NULL, 'Cannot autowire service ".service_locator.KKWZSFE": it references class "App\\Entity\\Program" but no such service exists.'],
        ], [
            'entityManager' => '?',
            'program' => 'App\\Entity\\Program',
        ]);
    }
}
