<?php

namespace ContainerOurMZCE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_3nrNJeCService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.3nrNJeC' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.3nrNJeC'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'actor' => ['privates', '.errored..service_locator.3nrNJeC.App\\Entity\\Actor', NULL, 'Cannot autowire service ".service_locator.3nrNJeC": it references class "App\\Entity\\Actor" but no such service exists.'],
        ], [
            'actor' => 'App\\Entity\\Actor',
        ]);
    }
}
