<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container7cvuXgy\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container7cvuXgy/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container7cvuXgy.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container7cvuXgy\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container7cvuXgy\App_KernelDevDebugContainer([
    'container.build_hash' => '7cvuXgy',
    'container.build_id' => '8ff1a441',
    'container.build_time' => 1609949996,
], __DIR__.\DIRECTORY_SEPARATOR.'Container7cvuXgy');
